### PR TITLE
[RFR] Fixed an issue with non-button toggles

### LINKED ISSUE #23: Non interactive elements can't be controlled via keyboard
Even with `role="button"` and `tabindex="0"`. The toggle can be tabbed too, but not triggered.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

> Buttons are interactive controls and thus focusable. If the button role is added to an element that is not focusable by itself (such as `<span>`, `<div>` or `<p>`) then, the tabindex attributes have to be used to make the button focusable.
> 
> But if another tag is used  to create a custom button, the onclick event will only fire when clicked by the mouse cursor, even if role="button" is used. Because of this, the developer will have to surely add a separate key event handler to the element so that the button can be triggered,even  when the space key is pressed.

Needs some javascript to capture the keyboard events for non-interactive elements

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Fix #23.

### CODE REVIEW

**Comment by smartmike** [comment]
Yes.

File: a11y-toggle.js [hunk 1]
```diff
@@ -54,20 +70,11 @@
...
-  document.addEventListener('click', function (event) {
-    var toggle = getClosestToggle(event.target);
-    var target = toggle && targetsMap[toggle.getAttribute('aria-controls')];
-
-    if (!target) {
-      return false;
+  document.addEventListener('click', handleToggle);
+  document.addEventListener('keyup', function (event) {
+    if (event.which === 13 || event.which === 32) {
+      var toggle = getClosestToggle(event.target);
```
Comment (KittyGiraudel) [inline a11y-toggle.js:79]: We compute this twice, which is not great.

**Comment by smartmike** [comment]
Looks great
